# =============================================================================
# 文件名:   home/migration.nix
# 功能描述: 从 ~/.config/ 迁移至 Home Manager 管理的配置文件
# 说明:     所有之前未受 Nix 管理的配置文件统一在此管理，
#           确保系统配置的完整可复现性
# =============================================================================
{ config, pkgs, ... }:

{
  # ===========================================================================
  # Fuzzel 应用启动器配置
  # ===========================================================================
  xdg.configFile = {
    # --- Fuzzel 主配置（引用 Noctalia 主题） ---
    "fuzzel/fuzzel.ini" = {
      force = true;
      text = ''
        include=~/.config/fuzzel/themes/noctalia
      '';
    };

    # --- Fuzzel Noctalia 主题（Niri Mod+D 快捷键依赖） ---
    "fuzzel/themes/noctalia" = {
      force = true;
      text = ''
        # Fuzzel Colors
        # Generated by Noctalia's Template Processor

        [colors]
        background=111415CC
        text=e1e3e4ff
        prompt=b3cad5ff
        placeholder=c4c3ebff
        input=5ed4fdff
        match=c4c3ebff
        selection=5ed4fd80
        selection-text=e1e3e4ff
        selection-match=003544ff
        counter=b3cad5ff
        border=5ed4fdff
      '';
    };

    # =========================================================================
    # Noctalia Shell 配置
    # =========================================================================

    # --- Noctalia 配色方案 ---
    "noctalia/colors.json" = {
      force = true;
      text = builtins.toJSON {
        mPrimary = "#5ed4fd";
        mOnPrimary = "#003544";
        mSecondary = "#b3cad5";
        mOnSecondary = "#1e333c";
        mTertiary = "#c4c3eb";
        mOnTertiary = "#2d2d4d";
        mError = "#ffb4ab";
        mOnError = "#690005";
        mSurface = "#111415";
        mOnSurface = "#e1e3e4";
        mSurfaceVariant = "#1d2022";
        mOnSurfaceVariant = "#c0c8cc";
        mOutline = "#40484c";
      };
    };

    # --- Noctalia 设置 ---
    "noctalia/settings.json" = {
      force = true;
      text = builtins.toJSON {
        appLauncher = {
          autoPasteClipboard = false;
          clipboardWatchImageCommand = "wl-paste --type image --watch cliphist store";
          clipboardWatchTextCommand = "wl-paste --type text --watch cliphist store";
        };
      };
    };

    # --- Noctalia 插件源 ---
    "noctalia/plugins.json" = {
      force = true;
      text = builtins.toJSON {
        sources = [
          {
            enabled = true;
            name = "Noctalia Plugins";
            url = "https://github.com/noctalia-dev/noctalia-plugins";
          }
        ];
        states = { };
        version = 2;
      };
    };

    # =========================================================================
    # Alacritty Noctalia 主题（未启用，仅备份保留）
    # 当前 Alacritty 使用系统 Dracula 主题（见 home/alacritty.nix）
    # =========================================================================
    "alacritty/themes/noctalia.toml" = {
      force = true;
      text = ''
        [colors.primary]
        background = '#111415'
        foreground = '#e1e3e4'

        [colors.cursor]
        text = '#e1e3e4'
        cursor = '#c0c8cc'

        [colors.vi_mode_cursor]
        text = '#111415'
        cursor = '#5ed4fd'

        [colors.search.matches]
        foreground = '#40484c'
        background = '#c4c3eb'

        [colors.search.focused_match]
        foreground = '#40484c'
        background = '#5ed4fd'

        [colors.footer_bar]
        foreground = '#40484c'
        background = '#e1e3e4'

        [colors.hints.start]
        foreground = '#40484c'
        background = '#b3cad5'

        [colors.hints.end]
        foreground = '#40484c'
        background = '#b3cad5'

        [colors.selection]
        text = '#111415'
        background = '#5ed4fd'

        [colors.normal]
        black = '#181818'
        red = '#ffb4ab'
        green = '#5ed4fd'
        yellow = '#006781'
        blue = '#5ed4fd'
        magenta = '#c4c3eb'
        cyan = '#b3cad5'
        white = '#BAC2DE'

        [colors.bright]
        black = '#585B70'
        red = '#F38BA8'
        green = '#A6E3A1'
        yellow = '#F9E2AF'
        blue = '#89B4FA'
        magenta = '#F5C2E7'
        cyan = '#94E2D5'
        white = '#A6ADC8'

        [colors.dim]
        black = '#45475A'
        red = '#F38BA8'
        green = '#A6E3A1'
        yellow = '#F9E2AF'
        blue = '#89B4FA'
        magenta = '#F5C2E7'
        cyan = '#94E2D5'
        white = '#BAC2DE'
      '';
    };

    # =========================================================================
    # Qt 主题 Noctalia 配色
    # =========================================================================

    "qt5ct/colors/noctalia.conf" = {
      force = true;
      text = ''
        [ColorScheme]
        active_colors=#e1e3e4, #111415, #40484c, #cacaca, #9f9f9f, #1d2022, #e1e3e4, #ffffff, #e1e3e4, #111415, #111415, #000000, #004d62, #b9eaff, #b3cad5, #5ed4fd, #40484c, #111415, #40484c, #e1e3e4, #e1e3e4, #5ed4fd
        disabled_colors=#e1e3e4, #111415, #40484c, #cacaca, #9f9f9f, #1d2022, #e1e3e4, #ffffff, #e1e3e4, #111415, #111415, #000000, #004d62, #b9eaff, #b3cad5, #5ed4fd, #40484c, #111415, #40484c, #e1e3e4, #e1e3e4, #5ed4fd
        inactive_colors=#e1e3e4, #111415, #40484c, #cacaca, #9f9f9f, #1d2022, #e1e3e4, #ffffff, #e1e3e4, #111415, #111415, #000000, #004d62, #b9eaff, #b3cad5, #5ed4fd, #40484c, #111415, #40484c, #e1e3e4, #e1e3e4, #5ed4fd
      '';
    };

    "qt6ct/colors/noctalia.conf" = {
      force = true;
      text = ''
        [ColorScheme]
        active_colors=#e1e3e4, #111415, #40484c, #cacaca, #9f9f9f, #1d2022, #e1e3e4, #ffffff, #e1e3e4, #111415, #111415, #000000, #004d62, #b9eaff, #b3cad5, #5ed4fd, #40484c, #111415, #40484c, #e1e3e4, #e1e3e4, #5ed4fd
        disabled_colors=#e1e3e4, #111415, #40484c, #cacaca, #9f9f9f, #1d2022, #e1e3e4, #ffffff, #e1e3e4, #111415, #111415, #000000, #004d62, #b9eaff, #b3cad5, #5ed4fd, #40484c, #111415, #40484c, #e1e3e4, #e1e3e4, #5ed4fd
        inactive_colors=#e1e3e4, #111415, #40484c, #cacaca, #9f9f9f, #1d2022, #e1e3e4, #ffffff, #e1e3e4, #111415, #111415, #000000, #004d62, #b9eaff, #b3cad5, #5ed4fd, #40484c, #111415, #40484c, #e1e3e4, #e1e3e4, #5ed4fd
      '';
    };

    # =========================================================================
    # Niri 辅助脚本目录（已管理 edit-screenshot.sh，此处为占位）
    # =========================================================================

    # =========================================================================
    # Remmina 自启动
    # =========================================================================
    "autostart/remmina-applet.desktop" = {
      force = true;
      text = ''
        [Desktop Entry]
        Type=Application
        Name=Remmina Applet
        Comment=Remmina system tray applet
        Exec=remmina -i
        Icon=remmina
        StartupNotify=false
        X-GNOME-Autostart-enabled=true
        NoDisplay=false
        Hidden=false
      '';
    };
  };

  # ===========================================================================
  # 清理：移除 ~/.config/nix/nix.conf（GitHub Token 已移至 /etc/nix/）
  # ===========================================================================
  # home-manager 不直接删除文件，此处留空文件替代原 nix.conf
  # 实际的 GitHub Token 现在位于 /etc/nix/github-access-tokens（由 nix-settings.nix 引用）
}
